name: store_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  font_awesome_flutter: ^10.1.0
  http: ^0.13.6
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  dio: ^4.0.6
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  bot_toast: ^4.0.2
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  conditional_builder_null_safety: ^0.0.6
  carousel_slider: ^4.1.1
  flutter_svg: ^2.0.5
  animated_bottom_navigation_bar: ^0.3.3
  image_picker: ^0.8.7+4
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^2.3.3
  awesome_dialog: ^2.2.1
  animated_splash_screen: ^1.2.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  provider: ^6.0.5
  firebase_storage: ^11.1.2
  splash_screen_view: ^2.0.1
  firebase_messaging: ^14.5.0
  flutter_local_notifications: ^14.0.0+1
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.11
  flutter_animate: ^4.1.1+1





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_iconn"
  ios: true
  image_path: "assets/icon/Logo.jpeg"
flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/


  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/Janna_Bold.ttf
          weight: 700

    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf



